<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\InstructorWorkshop;
use carbon\Carbon;

class InstructorWorkshopSeeder extends Seeder
{    
    public function run(): void
    {
        $instructorWorkshops = [
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 1,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 2,
                'workshop_id' => 2,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 2,
                'workshop_id' => 2,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('16:00:00'),
                'end_time' => Carbon::parse('17:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 3,
                'workshop_id' => 3,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 1,
                'workshop_id' => 4,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 4,
                'workshop_id' => 4,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 5,
                'workshop_id' => 5,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 6,
                'workshop_id' => 6,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 7,
                'workshop_id' => 7,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('16:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 2B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 8,
                'workshop_id' => 8,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('09:00:00'),
                'end_time' => Carbon::parse('10:00:00'),                
                'max_capacity' => 25,
                'place' => 'Zoom',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 9,
                'workshop_id' => 9,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 9,
                'workshop_id' => 9,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 10,
                'workshop_id' => 10,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Tercer piso Edificio Piscina Temp.',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 2,
                'workshop_id' => 11,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 2,
                'workshop_id' => 11,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('16:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 18,
                'workshop_id' => 12,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('09:00:00'),
                'end_time' => Carbon::parse('10:30:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 11,
                'workshop_id' => 13,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('14:30:00'),
                'end_time' => Carbon::parse('16:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 2B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 12,
                'workshop_id' => 14,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:30:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 2B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 13,
                'workshop_id' => 15,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('16:30:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 2B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 14,
                'workshop_id' => 16,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Campo N° 4',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 15,
                'workshop_id' => 17,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('16:30:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 16,
                'workshop_id' => 18,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Ex Sala Spinning',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 17,
                'workshop_id' => 19,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('11:30:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 18,
                'workshop_id' => 12,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('14:30:00'),
                'end_time' => Carbon::parse('16:30:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 19,
                'workshop_id' => 20,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 19,
                'workshop_id' => 20,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('14:00:00'),
                'end_time' => Carbon::parse('16:00:00'),                
                'max_capacity' => 25,
                'place' => 'Zoom',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 20,
                'workshop_id' => 21,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('15:50:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 20,
                'workshop_id' => 21,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('15:50:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 21,
                'workshop_id' => 22,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 2B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 5,
                'workshop_id' => 23,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),                
                'max_capacity' => 25,
                'place' => 'Zoom',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 22,
                'workshop_id' => 24,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:30:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 23,
                'workshop_id' => 25,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('15:30:00'),
                'end_time' => Carbon::parse('17:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 22,
                'workshop_id' => 25,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('11:30:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 2B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 22,
                'workshop_id' => 26,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('17:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 24,
                'workshop_id' => 27,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('14:00:00'),
                'end_time' => Carbon::parse('16:00:00'),                
                'max_capacity' => 25,
                'place' => 'Sala 2B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 6,
                'workshop_id' => 28,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('11:30:00'),
                'end_time' => Carbon::parse('13:00:00'),                
                'max_capacity' => 25,
                'place' => 'Zoom',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 6,
                'workshop_id' => 28,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('10:30:00'),
                'end_time' => Carbon::parse('12:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 25,
                'workshop_id' => 29,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 25,
                'workshop_id' => 29,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 25,
                'workshop_id' => 29,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('12:00:00'),
                'end_time' => Carbon::parse('13:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 26,
                'workshop_id' => 30,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('09:30:00'),
                'end_time' => Carbon::parse('10:30:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 27,
                'workshop_id' => 31,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),
                'max_capacity' => 25,
                'place' => 'Piscina Temperada',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 27,
                'workshop_id' => 31,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),
                'max_capacity' => 25,
                'place' => 'Piscina Temperada',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 27,
                'workshop_id' => 31,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),
                'max_capacity' => 25,
                'place' => 'Piscina Temperada',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 27,
                'workshop_id' => 31,
                'day_of_week' => 4,
                'start_time' => Carbon::parse('11:00:00'),
                'end_time' => Carbon::parse('12:00:00'),
                'max_capacity' => 25,
                'place' => 'Piscina Temperada',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 28,
                'workshop_id' => 32,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('16:00:00'),
                'end_time' => Carbon::parse('17:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 28,
                'workshop_id' => 33,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('16:00:00'),
                'end_time' => Carbon::parse('17:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 29,
                'workshop_id' => 34,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('17:00:00'),
                'end_time' => Carbon::parse('18:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 30,
                'workshop_id' => 35,
                'day_of_week' => 1,
                'start_time' => Carbon::parse('10:30:00'),
                'end_time' => Carbon::parse('11:30:00'),
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 31,
                'workshop_id' => 36,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('14:30:00'),
                'end_time' => Carbon::parse('15:30:00'),
                'max_capacity' => 25,
                'place' => 'Sala 4A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 32,
                'workshop_id' => 37,
                'day_of_week' => 6,
                'start_time' => Carbon::parse('09:00:00'),
                'end_time' => Carbon::parse('10:30:00'),
                'max_capacity' => 25,
                'place' => 'Zoom',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 33,
                'workshop_id' => 38,
                'day_of_week' => 5,
                'start_time' => Carbon::parse('14:00:00'),
                'end_time' => Carbon::parse('15:30:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 5,
                'workshop_id' => 39,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('10:00:00'),
                'end_time' => Carbon::parse('11:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 5,
                'workshop_id' => 40,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('11:15:00'),
                'end_time' => Carbon::parse('12:15:00'),
                'max_capacity' => 25,
                'place' => 'Sala 4A',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 34,
                'workshop_id' => 41,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('16:00:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 34,
                'workshop_id' => 42,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('14:00:00'),
                'end_time' => Carbon::parse('14:50:00'),
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 34,
                'workshop_id' => 42,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('14:00:00'),
                'end_time' => Carbon::parse('14:50:00'),
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 34,
                'workshop_id' => 42,
                'day_of_week' => 3,
                'start_time' => Carbon::parse('15:00:00'),
                'end_time' => Carbon::parse('15:50:00'),
                'max_capacity' => 25,
                'place' => 'Sala 4B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            [
                'instructor_id' => 34,
                'workshop_id' => 43,
                'day_of_week' => 2,
                'start_time' => Carbon::parse('16:00:00'),
                'end_time' => Carbon::parse('16:50:00'),
                'max_capacity' => 25,
                'place' => 'Sala 3B',
                'initial_monthly_period_id' => 7,
                'is_active' => true,
            ],
            
        ];

        foreach ($instructorWorkshops as $iw) {
            InstructorWorkshop::create($iw);
            /* $iw = InstructorWorkshop::create($iw);
            app(\App\Observers\InstructorWorkshopObserver::class)->created($iw); */
        }
    }
}
