<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Workshop;

class WorkshopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $workshops = [
            [
                'name' => 'Actividad Física',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Baile',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Baile Ondo',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Gimnasia aeróbica',	
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Happy Taiso',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Karaoke - En español',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'NIHONGO - Básico',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Pulseras MACRAMÉ',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Tai Chi',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Tenis de mesa',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Terapia musical Yura',
                'description' => null,
                'duration_hours' => null,
                'price' => 20,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Baile Odori',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Bijouteria',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Cocina',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Computación - Básico',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Gateball',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Karaoke - Música variada',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Taiko',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Tejido a crochet',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Karaoke - En japonés',
                'description' => null,
                'duration_hours' => null,
                'price' => 35,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Ejercicios terapéuticos',
                'description' => null,
                'duration_hours' => null,
                'price' => 50,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Sanshin',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Yoga en silla - Virtual',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Uso de laptop - Básico',
                'description' => null,
                'duration_hours' => null,
                'price' => 40,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Uso de Smart - Inicial',
                'description' => null,
                'duration_hours' => null,
                'price' => 40,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Diseño Gráfico',
                'description' => null,
                'duration_hours' => null,
                'price' => 45,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Amigurumi',
                'description' => null,
                'duration_hours' => null,
                'price' => 40,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Agilidad Mental',
                'description' => null,
                'duration_hours' => null,
                'price' => 50,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Cardio Dance',
                'description' => null,
                'duration_hours' => null,
                'price' => 25,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Dibujo y Pintura',
                'description' => null,
                'duration_hours' => null,
                'price' => 50,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Ejercicios en el agua',
                'description' => null,
                'duration_hours' => null,
                'price' => 50,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Danzas Peruanas',
                'description' => null,
                'duration_hours' => null,
                'price' => 35,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Marinera Norteña',
                'description' => null,
                'duration_hours' => null,
                'price' => 35,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Percusión',
                'description' => null,
                'duration_hours' => null,
                'price' => 60,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Meditación Guiada',
                'description' => null,
                'duration_hours' => null,
                'price' => 35,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Pilates',
                'description' => null,
                'duration_hours' => null,
                'price' => 40,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Estimulación Cognitiva',	
                'description' => null,
                'duration_hours' => null,
                'price' => 50,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Memoria Activa',
                'description' => null,
                'duration_hours' => null,
                'price' => 50,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Yoga en Silla',
                'description' => null,
                'duration_hours' => null,
                'price' => 35,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Yoga en Mat',
                'description' => null,
                'duration_hours' => null,
                'price' => 40,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Música y Canto',
                'description' => null,
                'duration_hours' => null,
                'price' => 60,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Teclado',
                'description' => null,
                'duration_hours' => null,
                'price' => 60,
                'max_students' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Técnicas de Karaoke',
                'description' => null,
                'duration_hours' => null,
                'price' => 60,
                'max_students' => null,
                'status' => 'active',
            ],
        ];

        foreach ($workshops as $workshop) {
            Workshop::create($workshop);
        }
    }
}
