<?php

namespace Database\Seeders;

use App\Models\Workshop;
use Illuminate\Database\Seeder;

class WorkshopSeeder extends Seeder
{
    public function run(): void
    {
        $workshops = [
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '11:05:00',
                'duration' => 55,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Actividad Física',
                'instructor_id' => 1,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Baile',
                'instructor_id' => 2,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Baile',
                'instructor_id' => 2,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '16:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Baile Ondo',
                'instructor_id' => 3,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Gimnasia aeróbica',
                'instructor_id' => 4,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Happy Taiso',
                'instructor_id' => 5,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Karaoke - En español',
                'instructor_id' => 6,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'NIHONGO - Básico',
                'instructor_id' => 7,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '15:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Pulseras MACRAMÉ',
                'instructor_id' => 8,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '09:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Tai Chi',
                'instructor_id' => 9,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Tai Chi',
                'instructor_id' => 9,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Tenis de mesa',
                'instructor_id' => 10,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Terapia musical Yura',
                'instructor_id' => 2,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Terapia musical Yura',
                'instructor_id' => 2,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '15:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 25,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Baile Odori',
                'instructor_id' => 18,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '14:30:00',
                'duration' => 120,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Baile Odori',
                'instructor_id' => 18,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '18:00:00',
                'duration' => 75,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Cocina',
                'instructor_id' => 12,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '10:00:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Computación - Básico',
                'instructor_id' => 13,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '15:00:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Gateball',
                'instructor_id' => 14,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '10:00:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Karaoke - Música variada',
                'instructor_id' => 15,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '15:00:00',
                'duration' => 120,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Taiko',
                'instructor_id' => 16,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Tejido a crochet',
                'instructor_id' => 17,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '11:30:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Karaoke - En japonés',
                'instructor_id' => 19,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '11:00:00',
                'duration' => 120,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Karaoke - En japonés',
                'instructor_id' => 19,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '14:00:00',
                'duration' => 120,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Sanshin',
                'instructor_id' => 21,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '09:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Sanshin',
                'instructor_id' => 21,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '09:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Yoga en silla - Virtual',
                'instructor_id' => 5,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Uso de laptop - Básico',
                'instructor_id' => 22,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '10:00:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Uso de Smart - Inicial',
                'instructor_id' => 23,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '15:30:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Uso de Smart - Inicial',
                'instructor_id' => 23,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '11:30:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Diseño Gráfico',
                'instructor_id' => 22,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '15:30:00',
                'duration' => 120,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 45,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Amigurumi',
                'instructor_id' => 24,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '14:00:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Agilidad Mental',
                'instructor_id' => 6,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '11:30:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Agilidad Mental',
                'instructor_id' => 6,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '10:30:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Cardio Dance',
                'instructor_id' => 25,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Cardio Dance',
                'instructor_id' => 25,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Cardio Dance',
                'instructor_id' => 25,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '12:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 30,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Dibujo y Pintura',
                'instructor_id' => 26,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '09:30:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 50,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Ejercicios en el agua',
                'instructor_id' => 27,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Ejercicios en el agua',
                'instructor_id' => 27,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Ejercicios en el agua',
                'instructor_id' => 27,
                'description' => null,
                'day_of_week' => 'Jueves',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Danzas Peruanas',
                'instructor_id' => 28,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '16:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Marinera Norteña',
                'instructor_id' => 28,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '16:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Percusión',
                'instructor_id' => 29,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '17:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Meditación Guiada',
                'instructor_id' => 30,
                'description' => null,
                'day_of_week' => 'Lunes',
                'start_time' => '10:30:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 20,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Pilates',
                'instructor_id' => 31,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '14:30:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Estimulación Cognitiva',
                'instructor_id' => 32,
                'description' => null,
                'day_of_week' => 'Sábado',
                'start_time' => '09:00:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Memoria Activa',
                'instructor_id' => 33,
                'description' => null,
                'day_of_week' => 'Viernes',
                'start_time' => '14:00:00',
                'duration' => 90,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Yoga en Silla',
                'instructor_id' => 5,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '10:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Yoga en Mat',
                'instructor_id' => 5,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '11:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 40,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Música y Canto',
                'instructor_id' => 34,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '15:00:00',
                'duration' => 50,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Teclado',
                'instructor_id' => 34,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '14:00:00',
                'duration' => 60,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Teclado',
                'instructor_id' => 34,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '14:00:00',
                'duration' => 50,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Teclado',
                'instructor_id' => 34,
                'description' => null,
                'day_of_week' => 'Miércoles',
                'start_time' => '15:00:00',
                'duration' => 50,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
            [
                'name' => 'Técnicas de Karaoke',
                'instructor_id' => 34,
                'description' => null,
                'day_of_week' => 'Martes',
                'start_time' => '16:00:00',
                'duration' => 50,
                'capacity' => 20,
                'number_of_classes' => 4,
                'standard_monthly_fee' => 60,
                'monthly_period_id' => 9,
            ],
        ];

        foreach ($workshops as $workshop) {
            Workshop::create($workshop);
        }
    }
}
